version: '3.8'

services:
  mongodb:
    image: mongo:7.0.5  # Latest stable MongoDB version
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"  # Expose MongoDB port
    environment:
      MONGO_INITDB_ROOT_USERNAME: root        # Root username
      MONGO_INITDB_ROOT_PASSWORD: password    # Root password (change this to a secure password)
      MONGO_INITDB_DATABASE: product-service  # Initial database (ensure this is correct)
    volumes:
      - mongo_data:/data/db  # Persist MongoDB data
      - mongo_config:/data/configdb  # Store MongoDB config
    networks:
      - mongo_network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s

networks:
  mongo_network:
    driver: bridge

volumes:
  mongo_data:
    driver: local
  mongo_config:
    driver: local
