spring:
  application:
    name: product-service

  data:
    mongodb:
      uri: mongodb://${MONGO_DB_USER}:${MONGO_DB_PASSWORD}@localhost:27017/product-service?authSource=${AUTH_SOURCE}
  profiles:
    active: dev
